# Global configuration
date_check: true
api_url: "https://overpass-api.de/api/interpreter"
cache_dir: "~/.cache/osm-power"
force_refresh: false
enable_estimation: true
enable_clustering: false

# Power source configurations
sources:
  solar:
    clustering:
      method: hdbscan
      to_radians: true
      metric: haversine
      cluster_selection_epsilon: 0.00000785
      min_cluster_size: 5
      cluster_selection_method: eom
      core_dist_n_jobs: 4
    estimation:
      method: area_based
      efficiency: 150  # W/m2

  wind:
    clustering:
      method: dbscan
      to_radians: false
      eps: 0.009
      min_samples: 2
    estimation:
      method: default_value
      default_capacity: 2000  # kW

  biomass:
    clustering:
      method: dbscan
      to_radians: false
      eps: 0.0018
      min_samples: 2

# Logging configuration
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# Output configuration
output:
  csv_dir: "./output/csv"
  plot_dir: "./output/plots"

# Algorithm parameters (for reference)
algorithm_params:
  hdbscan:
    - min_cluster_size
    - min_samples
    - cluster_selection_epsilon
    - max_cluster_size
    - metric
    - alpha
    - p
    - algorithm
    - leaf_size
    - memory
    - approx_min_span_tree
    - gen_min_span_tree
    - core_dist_n_jobs
    - cluster_selection_method
    - allow_single_cluster
    - prediction_data
    - branch_detection_data
    - match_reference_implementation
    - cluster_selection_epsilon_max
  dbscan:
    - eps
    - min_samples
    - metric
    - metric_params
    - algorithm
    - leaf_size
    - p
    - n_jobs
  kmeans:
    - n_clusters
    - init
    - n_init
    - max_iter
    - tol
    - verbose
    - random_state
    - copy_x
    - algorithm