power_output:
  generator:output:hot_water:
    type: numeric
    unit: kW
    description: Hot water output of generator
  generator:output:cold_water:
    type: numeric
    unit: kW
    description: Cold water output of generator
  plant:output:electricity:
    type: numeric
    unit: kW
    description: Electrical power output of plant
  plant:output:hot_water:
    type: numeric
    unit: kW
    description: Hot water output of plant
  plant:output:cold_water:
    type: numeric
    unit: kW
    description: Cold water output of plant
  plant:output:biogas:
    type: numeric
    unit: kW
    description: Biogas output of plant
  generator:output:electricity:
    type: numeric
    unit: kW
    description: Electrical power output of generator
physical_dimensions:
  height:hub:
    type: numeric
    unit: m
    description: Height of generator hub
  rotor:diameter:
    type: numeric
    unit: m
    description: Diameter of rotor
temporal:
  start_date:
    type: date
    description: Start date of operation
metadata:
  generator:method:
    type: categorical
    description: Method of power generation
  generator:source:
    type: categorical
    description: Source of power
  generator:type:
    type: categorical
    description: Type of generator
  plant:method:
    type: categorical
    description: Method of power generation for plant
  plant:source:
    type: categorical
    description: Source of power for plant
  plant:type:
    type: categorical
    description: Type of plant
  manufacturer:
    type: categorical
    description: Manufacturer of the equipment
  model:
    type: categorical
    description: Model of the equipment
  operator:
    type: categorical
    description: Operator of the facility
  name:
    type: text
    description: Name of the facility
  generator:solar:tracking:
    type: categorical
    description: Auto-added from analysis
  building:
    type: categorical
    description: Auto-added from analysis
  source:
    type: text
    description: Auto-added from analysis
  generator:plant:
    type: categorical
    description: Auto-added from analysis
unknown: {}
